###
# Climate
###
- platform: template
  sensors:
    living_room_ac_is_on:
      friendly_name: 'Living Room AC'
      value_template: >-
        {% if is_state('climate.slvn', 'off') %}
          False
        {% else %}
          True
        {% endif %}
      icon_template: >-
        {% if is_state('binary_sensor.living_room_ac_is_on', 'on') %}
          mdi:hvac
        {% else %}
          mdi:hvac-off
        {% endif %}
    master_bedroom_ac_is_on:
      friendly_name: 'Master Bedroom AC'
      value_template: >-
        {% if is_state('climate.shynh', 'off') %}
          False
        {% else %}
          True
        {% endif %}
      icon_template: >-
        {% if is_state('binary_sensor.master_bedroom_ac_is_on', 'on') %}
          mdi:hvac
        {% else %}
          mdi:hvac-off
        {% endif %}

- platform: threshold
  name: 'Master bedroom temperature threshold'
  entity_id: sensor.master_bedroom_sensibo_temperature
  lower: '21'
  upper: '25'
- platform: threshold
  name: 'Living room temperature threshold'
  entity_id: sensor.living_room_temperature
  lower: '21'
  upper: '25'
