##############################################
#               BINARY SENSORS               #
##############################################
# Random Boolean sensor
- platform: random
  name: 'Random Boolean'
