###
# TV
###
# Return True when Netflix is playing
- platform: template
  sensors:
    netflix_on:
      friendly_name: 'Netflix on'
      value_template: >-
        {{ state_attr('media_player.mibox3', 'app_name') == 'Netflix' }}
# Return True when YouTube is playing
- platform: template
  sensors:
    youtube_on:
      friendly_name: 'YouTube on'
      value_template: >-
        {{ state_attr('media_player.mibox3', 'app_name') == 'YouTube' }}
