#######################################
#               CLIMATE               #
#######################################
###
# Define climate
# https://www.home-assistant.io/integrations/climate
###

# Sensibo devices
- platform: sensibo
  api_key: !secret sensibo

# Living room Thermostat
- platform: generic_thermostat
  name: 'Living Room Thermostat'
  heater: switch.living_room_ac_switch
  ac_mode: true
  target_sensor: sensor.living_room_temperature
  min_temp: 22
  max_temp: 26
  target_temp: 25
  min_cycle_duration:
    minutes: 5
  keep_alive:
    minutes: 30
