######################################
#               CAMERA               #
######################################
###
# Define cameras
# https://www.home-assistant.io/integrations/camera
###

# Vacuum map camera using @PiotrMachowski awesome custom integration
# https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor
- platform: xiaomi_cloud_map_extractor
  name: "Vacuum map"
  host: !secret vacuum_host
  token: !secret vacuum_token
  username: !secret xiaomi_cloud_username
  password: !secret xiaomi_cloud_password
  country: "sg"
  scan_interval: 30
  draw:
    - charger
    - path
    - vacuum_position
  room_colors:
    1: [240, 178, 122]
    2: [133, 193, 233]
    3: [217, 136, 128]
    4: [52, 152, 219]
    5: [205, 97, 85]
    6: [243, 156, 18]
    7: [88, 214, 141]
    8: [245, 176, 65]
    9: [252, 212, 81]
    10: [72, 201, 176]
