##################################################
#     Home Assistant Main Configuration File     #
#            Yuval Aboulafia - 062020            #
##################################################

##################################################
#                      CORE                      #
##################################################
# Home Assistant core settings.
homeassistant:
  # Name of the location where Home Assistant is running.
  name: Home
  # Location required to calculate the time the sun rises and sets.
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters).
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial.
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
  time_zone: Asia/Jerusalem
  # Customizing entities.
  customize: !include customize.yaml

# Allows Home Assistant mobile app to easily integrate with Home Assistant.
mobile_app:

# Serves all files and data required for the Home Assistant frontend.
#http:

# Exposes a RESTful API and allows one to interact with a Home Assistant instance that is running headless.
#api:

##################################################
#                       GUI                      #
##################################################
# Enables the frontend.
frontend:
  themes: !include_dir_merge_named themes

# Enables custom UI Settings.
lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml

# Enables configuration UI.
config:

# Enables a map showing the location of tracked devices.
map:

##################################################
#                     PERSONS                    #
##################################################
# Allows connecting device tracker entities to one or more person entities.
person: !include person.yaml

# Presence detection and tracking.
device_tracker: !include device_tracker.yaml

# Allow you to specify certain regions on earth.
zone: !include zone.yaml

##################################################
#                   DISCOVERY                    #
##################################################
# Discover some devices automatically.
discovery:
  ignore:
    - yeelight

# Discover some devices automatically.
zeroconf:

# Discover some devices automatically.
ssdp:

##################################################
#                  INTEGRATIONS                  #
##################################################
# Allows you to control the state of your Xiaomi Mi Robot Vacuum.
#vacuum:
#  - platform: xiaomi_miio
#    host: !secret vacuum_host
#    token: !secret vacuum_token

#media_player:
#  - platform: androidtv
#    host: !secret tv_host
#    name: Pilot-TV
#    adb_server_ip: !secret localhost

# Uses the Speedtest.net web service to measure network bandwidth performance.
speedtestdotnet:

# Allows the user to define date and time values.
input_datetime:
  both_date_and_time:
    name: Input with both date and time
    has_date: true
    has_time: true
  only_date:
    name: Input with only date
    has_date: true
  only_time:
    name: Input with only time
    has_time: true

# Displays a variety of information related to the Jewish Calendar as a variety of sensors.
jewish_calendar:
  language: hebrew

# Allows you to monitor the system information provided by the Glances API.
glances:

# Connect to your Google Calendars and generate binary sensors.
#google:
#  client_id: !secret gcalendar_id
#  client_secret: !secret gcalendar_client_secret

# Allows you to control your Yeelight Wifi bulbs with Home Assistant.
yeelight: !include yeelight.yaml

#notify:
#  - platform: discord
#    name: Discord
#    token: !secret discord_bot

# Allows you to retrieve statistics and interact with a Pi-hole system.
pi_hole:
  host: !secret nanopi_neo2
  api_key: !secret pi_hole_key

# Integrates Sensibo Air Conditioning controller into Home Assistant.
climate:
  - platform: sensibo
    api_key: !secret sensibo

# Proxmox VE is an open-source server virtualization environment. Allows you to poll various data from your instance.
proxmoxve:
  - host: !secret server
    username: !secret proxmox_user
    password: !secret proxmox_passwd
    verify_ssl: false
    realm: pve
    nodes:
      - node: pve
        vms:
          - 100
          - 101

##################################################
#                    LOG COMPONENTS              #
##################################################
# Enables support for tracking state changes over time.
history: !include history_exclude.yaml

# View events in a logbook
logbook: !include log_exclude.yaml

# Stores details in a database, which then are handled by the history integration.
recorder:
  db_url: !secret mariadb_address
  purge_keep_days: 30
  exclude:
    entities:
      - sensor.time
      - sensor.time_date
      - sensor.date
      - sensor.date_time
    domains:
      - sun
      - weather

# Set the default level for the logger.
logger:
  default: warning

# Stores information about all logged errors and warnings in Home Assistant.
system_log:
  max_entries: 150

##################################################
#                     COMPONENTS                 #
##################################################
# Checks daily for new releases.
updater:
  reporting: false

# Track the sun.
sun:

# System health.
system_health:

# Python scripts that are exposed as services in Home Assistant.
#python_script:

##################################################
#                     DOMAINS                    #
##################################################
group: !include group.yaml
automation: !include_dir_merge_list automation/
sensor: !include_dir_merge_list  sensor/
binary_sensor: !include_dir_merge_list binary_sensor/
utility_meter: !include utility_meter.yaml
timer: !include timer.yaml
switch: !include switch.yaml
light: !include light.yaml
input_boolean: !include input_boolean.yaml
#input_number: !include input_number.yaml
input_select: !include input_select.yaml
#input_text: !include input_text.yaml
script: !include_dir_merge_list script.yaml/
#shell_command: !include shell_command.yaml
