---
version: '3.4'

services:
  homeassistant:
    restart: always
    hostname: homeassistant
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    environment:
      - TZ=Asia/Jerusalem
    volumes:
      - /home/homeassistant/homeassistant/homeassistant/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    dns:
      - ${PIHOLE}

  postgres:
    restart: always
    hostname: postgres
    container_name: postgres
    image: postgres:latest
    network_mode: host
    ports:
      - 35432:5432
    environment:
        PUID: ${LOCAL_USER}
        PGID: ${LOCAL_USER}
        TZ: "Asia/Jerusalem"
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: HADB
    volumes:
        - /home/homeassistant/postgres/data:/var/lib/postgresql/data
