---
version: '3.4'

services:
    homeassistant:
        restart: always
        hostname: homeassistant
        container_name: homeassistant
        image: homeassistant/home-assistant:latest
        environment:
            TZ: "Asia/Jerusalem"
        volumes:
            - /home/homeassistant/homeassistant/homeassistant/config:/config
            - /var/run/docker.sock:/var/run/docker.sock
        network_mode: "host"
