#############################################
#                  SWITCHES                 #
#############################################
- platform: template
  switches:
    shabat_mode:
      friendly_name: 'מצב שבת'
      unique_id: 6ec56ed5-d5f0-45ee-a468-789d82332db2
      value_template: >-
        {{ states('input_boolean.shabat_mode') }}
      turn_on:
        - service: input_boolean.turn_on
          data:
            entity_id: input_boolean.shabat_mode
        - service: switch.turn_on
          data:
            entity_id: switch.living_room_shabat_select
        - service: switch.turn_on
          data:
            entity_id: switch.bathroom_shabat_select
      turn_off:
        - service: input_boolean.turn_off
          data:
            entity_id: input_boolean.shabat_mode
        - service: switch.turn_off
          data:
            entity_id: switch.living_room_shabat_select
        - service: switch.turn_off
          data:
            entity_id: switch.bathroom_shabat_select
      icon_template: >-
        {% if is_state('switch.shabat_mode', 'on') %}
          mdi:motion-sensor-off
        {% else %}
          mdi:motion-sensor
        {% endif %}

- platform: template
  switches:
    night_light_override:
      unique_id: 4e9a2793-1a7b-4b16-aa84-1958b6264791
      friendly_name: 'Night Light Override'
      value_template: >-
        {{ states('input_boolean.night_light_override') }}
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.night_light_override
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.night_light_override
      icon_template: >-
        {% if is_state('switch.night_light_override', 'on') %}
          mdi:shield
        {% else %}
          mdi:shield-off
        {% endif %}
