###########################################
#               LOVELACE-UI               #
###########################################
###
# Define views
# https://www.home-assistant.io/lovelace
###

title: 'Aboulafia Home'
views:
  - !include lovelace/ui-lovelace/overview.yaml
#  - !include lovelace/ui-lovelace/floorplan.yaml
  - !include lovelace/ui-lovelace/living_room.yaml
  - !include lovelace/ui-lovelace/master_bedroom.yaml
#  - !include lovelace/ui-lovelace/bedroom.yaml
  - !include lovelace/ui-lovelace/bathroom.yaml
  - !include lovelace/ui-lovelace/home_office.yaml
  - !include lovelace/ui-lovelace/stats.yaml
  - !include lovelace/ui-lovelace/extra.yaml
  - !include lovelace/ui-lovelace/system.yaml
