###
# Define custom header
# https://maykar.github.io/custom-header/#intro/intro
###
custom_header:
  compact_mode: true
  background: var(--primary-background-color);

####################################################
#                     CONFIG VIEWS                 #
####################################################
title: 'Aboulafia Home'
views:
  - !include lovelace/ui-lovelace/overview.yaml
  - !include lovelace/ui-lovelace/living_room.yaml
  - !include lovelace/ui-lovelace/master_bedroom.yaml
#  - !include lovelace/ui-lovelace/bedroom.yaml
  - !include lovelace/ui-lovelace/bathroom.yaml
  - !include lovelace/ui-lovelace/home_office.yaml
  - !include lovelace/ui-lovelace/stats.yaml
  - !include lovelace/ui-lovelace/system.yaml

####################################################
#                    EXTRA STUFF                   #
####################################################
  - id: extra_stuff
    title: 'Extra Stuff'
    icon: mdi:information-outline
    cards:
      - type: entities
        entities:
          - type: custom:hui-element
            card_type: picture
            image: 'https://brands.home-assistant.io/seventeentrack/logo.png'
          - type: custom:hui-element
            card_type: glance
            entities:
              - entity: sensor.seventeentrack_packages_not_found
                name: 'Not-Found'
              - entity: sensor.seventeentrack_packages_in_transit
                name: 'In-Transit'
              - entity: sensor.seventeentrack_packages_ready_to_be_picked_up
                name: 'Ready to be Picked-Up'
          - type: custom:auto-entities
            card:
              type: entities
              title: 'Package List'
              show_header_toggle: false
            filter:
              include:
                - entity_id: 'sensor.seventeentrack_package_*'

      - type: custom:banner-card
        heading: "\U0001F382 Birthdays"
        background: "#E64B51"
        row_size: 2
        entities:
          - entity: sensor.birthday_yuval
          - entity: sensor.birthday_tohar
#          - entity: sensor.anniversary_harel_nissim_birthday
#          - entity: sensor.anniversary_rotem_david_birthday
#          - entity: sensor.anniversary_marriage_anniversary
