####
# Climate
###

- alias: "Turn off Living-Room AC at night"
  id: 5f250d83-aa9a-4e2a-af61-8ad83f39a75a
  trigger:
    platform: time
    at: '21:00:00'
  condition: >-
    "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'off') }}"
  action:
    service: climate.turn_off
    data:
      entity_id: climate.living_room_heat_thermostat
