###
# EATON E5 650i
###
- platform: nut
  name: "EATON E5 650i"
  host: !secret rpi2
  username: !secret ups_user
  password: !secret ups_passwd
  resources:
    - battery.charge
    - battery.runtime
    - ups.load
    - ups.status
    - ups.status.display
    - input.voltage
    - output.frequency
    - output.voltage
    - output.voltage.nominal
