---

- platform: waze_travel_time
  name: "Yuval - From home to work"
  origin: !secret home_coordinates
  destination: !secret yuval_work_coordinates
  region: 'IL'
  avoid_toll_roads: true

- platform: waze_travel_time
  name: "Yuval - From work to home"
  origin: !secret yuval_work_coordinates
  destination: !secret home_coordinates
  region: 'IL'
  avoid_toll_roads: true

- platform: waze_travel_time
  name: "Yuval - Current location to home"
  origin: device_tracker.yuval
  destination: !secret home_coordinates
  region: 'IL'
  avoid_toll_roads: true
