###
# Shabbat
###

shabbat_lights_off_time:
  name: "Shabbat turn off light time"
  icon: mdi:clock
  initial: '21:00'
  options:
    - '20:30'
    - '20:45'
    - '21:00'
    - '21:15'
    - '21:30'
    - '21:45'
    - '22:00'
    - '22:15'
    - '22:30'
    - '22:45'
    - '23:00'
