---
# TODO: make card use auto-entities to populate
openings:
  card:
    type: glance
    entities:
      - entity: binary_sensor.[[room]]_door
        name: "Door"
      - entity: binary_sensor.[[room]]_window
        name: "Window"
