###
# Ping
###

- platform: ping
  host: !secret vacuum
  name: "Vacuum"
  count: 2
- platform: ping
  host: !secret laptop
  name: "Laptop"
  count: 2
- platform: ping
  host: !secret nanopi_neo2
  name: "NanoPi-NEO2"
  count: 2
- platform: ping
  host: !secret tv
  name: "TV"
  count: 2
- platform: ping
  host: !secret printer
  name: "Printer"
  count: 2
- platform: ping
  host: !secret rpi2
  name: "Raspberry-Pi2"
  count: 2
