###
# Steam
###
# Return True when a game is playing
- platform: template
  sensors:
    steam_game_on:
      friendly_name: "Steam Playing"
      icon_template: mdi:steam
      value_template: >-
        {{ not is_state('sensor.steam_game', 'unknown') }}
