---

- platform: tod
  name: "Night"
  after: sunset
  before: sunrise

- platform: tod
  name: "Day"
  after: sunrise
  before: sunset

- platform: template
  sensors:
    is_friday:
      friendly_name: "Friday"
      value_template: >-
        {{ now().weekday() == 4 }}
      icon_template: mdi:calendar-today
    is_sunday:
      friendly_name: "Sunday"
      value_template: >-
        {{ now().weekday() == 6 }}
      icon_template: mdi:calendar-today
