###
# AC Switches
###
- platform: template
  switches:
    living_room_ac_switch:
      friendly_name: "Living Room AC"
      value_template: >-
        {{ not is_state('climate.slvn', 'off') }}
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.slvn
          hvac_mode: cool
      turn_off:
        service: climate.turn_off
        data:
          entity_id: climate.slvn
      icon_template: >-
        {% if is_state('switch.living_room_ac_switch', 'on') %}
          mdi:hvac
        {% else %}
          mdi:hvac-off
        {% endif %}
