###
# UPS
###

- alias: "Notify for power outage and restore"
  id: 151f5012-4ee2-4372-926c-81746b3e7f76
  trigger:
    - platform: state
      entity_id: sensor.ups_status
      to: 'On Battery'
    - platform: state
      entity_id: sensor.ups_status
      to: 'Online'
  action:
    - choose:
      - conditions:
        - condition: state
          entity_id: sensor.ups_status
          state: 'On Battery'
        sequence:
          - service: notify.family
            data:
              message: "EMERGENCY POWER ONLY"
      - conditions:
        - condition: state
          entity_id: sensor.ups_status
          state: 'Online'
        sequence:
          - service: notify.family
            data:
              message: "POWER RESTORED, ALL SYSTEMS ONLINE"
