home_lat: 00.000000
home_lon: 00.000000
elevation: 00

gateway: 127.0.0.1
nanopi_neo2: 127.0.0.1
tv: 127.0.0.1
server: 127.0.0.1
printer: 127.0.0.1
rpi2: 127.0.0.1
laptop: 127.0.0.1
vacuum: 127.0.0.1
mibox_host: 127.0.0.1

proxmox_user: ''
proxmox_passwd: ''

17track_user: ''
17track_passwd: ''

ups_user: ''
ups_passwd: ''

xiaomi_cloud_username: ''
xiaomi_cloud_password: ''

accuweather: ''
steam_api: ''
sensibo: ''
pi_hole_key: ''
vacuum_token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

#mariadb_address: mysql://homeassistant:sometoken@core-mariadb/homeassistant?charset=utf8
