---

play_friday:
  sequence:
    - service: media_player.play_media
      target:
        entity_id: media_player.googlehome3668
      data:
        media_content_id: "https://open.spotify.com/playlist/6YVg7ELU3S7cezvQmrTzIy?si=Y_o1GufwSvuxPlx8oo1COQ"
        media_content_type: playlist
