###
# Shabat lights sequence
###
# Shabat and Chag lighting
shabat_chag_lighting_sequence:
  alias: "shabat and chag lighting sequence"
  description: "Sequence that notify when Shabat enters"
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.public_lights
        effect: Random Loop
    - delay: '00:00:03'
    - service: light.turn_on
      data:
        entity_id: light.public_lights
        effect: Stop
    - service: scene.turn_on
      entity_id: scene.shabat_eve

shabat_chag_end_lighting_sequence:
  alias: "shabat and chag lighting sequence"
  description: "Sequence that notify when Shabat ends"
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.public_lights
        effect: Random Loop
    - delay: '00:00:03'
    - service: light.turn_on
      data:
        entity_id: light.public_lights
        effect: Stop
    - service: scene.turn_on
      entity_id: scene.shabat_end
