###
# Motion
###

# Light-up night lights on movement detection
- alias: "Turn on lights when movement detected at night"
  id: bbe9c72e-6578-4fd1-b25c-12908145ac14
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.night
          state: 'on'
        - condition: state
          entity_id: light.yeelight_color_living_room_2
          state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.yeelight_color_living_room_2
      kelvin: 3600
      brightness_pct: 2
# Start the lights timer after no movement detected
- alias: "Start the lights timer"
  id: 2c73b4e0-34cc-4cfd-984e-159f321faa64
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'off'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.night
          state: 'on'
        - condition: state
          entity_id: input_boolean.night_light_override
          state: 'off'
  action:
    service: timer.start
    data:
      entity_id: timer.motion_lights_night
# Turn off the lights when the timer ends
- alias: "Turn off lights when the timer is finished"
  id: 395fbb3d-01ec-477e-a5dc-aab76acef310
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.motion_lights_night
  condition:
    - condition: state
      entity_id: input_boolean.night_light_override
      state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.yeelight_color_living_room_2
      transition: 30
