###
# Motion
###

- alias: "Turn on lights when motion is detected at night"
  id: bbe9c72e-6578-4fd1-b25c-12908145ac14
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.night
      state: 'on'
    - condition: state
      entity_id: light.yeelight_color_living_room_2
      state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.yeelight_color_living_room_2
      kelvin: 3600
      brightness_pct: 2

- alias: "Turn-off the light"
  id: 2c73b4e0-34cc-4cfd-984e-159f321faa64
  mode: restart
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'off'
  condition:
    - condition: state
      entity_id: binary_sensor.night
      state: 'on'
    - condition: state
      entity_id: input_boolean.night_light_override
      state: 'off'
  action:
    - service: timer.start
      data:
        entity_id: timer.motion_lights_night
    - wait_for_trigger:
        platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.motion_lights_night
    - service: light.turn_off
      data:
        entity_id: light.yeelight_color_living_room_2
        transition: 30
