###
# Shabbat notifications
###

- alias: "Notify for candles"
  id: c5553611-fb7b-42d7-80af-2608a31c2c25
  trigger:
    platform: state
    entity_id: binary_sensor.shabbat_notification_trigger_30m
    to: 'on'
  condition:
    - condition: time
      weekday:
        - fri
    - condition: state
      entity_id: group.person
      state: 'home'
  action:
    - service: notify.mobile_app_yuval
      data:
        title: "שבת שלום!"
        message: "זכרת להכין מיחם ונרות?"
    - service: script.notify_for_shabbat

- alias: "Notify for Shabbat"
  id: 1145acf8-55b2-4564-bab8-94090f75d7d5
  trigger:
    platform: state
    entity_id: binary_sensor.shabbat_notification_trigger_10m
    to: 'on'
  condition:
    - condition: time
      weekday:
        - fri
    - condition: state
      entity_id: group.person
      state: 'home'
  action:
    service: notify.family
    data:
      title: "שבת שלום!"
      message: "שבת נכנסת בעוד 10 דקות."
