---

- alias: "Update notifications"
  id: 21a7799b-083b-45f4-af72-c4b6200fd25b
  description: "Send a notification when there's an update availiable for Home Assistant"
  trigger:
    platform: state
    entity_id: binary_sensor.updater
    to: 'on'
  action:
    - service: notify.mobile_app_yuval
      device_id: mobile_app.yuval
      data:
        title: "Update time!"
        message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available"
        color: "homeassistant"
  mode: restart
  max_exceeded: silent
