###
# WEATHER
###
# Outside temps
- platform: template
  sensors:
    outside_temps:
      friendly_name: 'Outside Temperature'
      unit_of_measurement: '°C'
      value_template: >-
        {{ state_attr('weather.openweathermap', 'temperature') | round }}
      icon_template: mdi:thermometer

# Wind sensors
- platform: template
  sensors:
    openweathermap_wind_speed:
      friendly_name: 'Wind speed'
      value_template: >-
        {{ state_attr('weather.openweathermap', 'wind_speed') | round }}
      icon_template: mdi:weather-windy
    wind_scale_friendly:
      friendly_name: 'Wind Scale'
      icon_template: >-
        {% set speed = (states('sensor.openweathermap_wind_speed') | float(-1) * 3600 / 1000) %}
        {% if speed >= 75 %}
          mdi:weather-tornado
        {% elif speed >= 39 %}
          mdi:weather-windy
        {% elif speed >= 0 %}
          mdi:airballoon
        {% else %}
          mdi:cloud-question
        {% endif %}
      value_template: >-
        {% set speed = (states('sensor.openweathermap_wind_speed') | float(-1) * 3600 / 1000) %}
        {% if speed >= 118 %}
          Hurricane force
        {% elif speed >= 103 %}
          Violent storm
        {% elif speed >= 89 %}
          Storm
        {% elif speed >= 75 %}
          Strong gale
        {% elif speed >= 62 %}
          Fresh gale
        {% elif speed >= 50 %}
          High wind
        {% elif speed >= 39 %}
          Strong breeze
        {% elif speed >= 29 %}
          Fresh breeze
        {% elif speed >= 20 %}
          Moderate breeze
        {% elif speed >= 12 %}
          Gentle breeze
        {% elif speed >= 6 %}
          Light breeze
        {% elif speed >= 1 %}
          Light air
        {% elif speed >= 0 %}
          Calm
        {% elif speed < 0 %}
          unknown
        {% endif %}

# UV Sensor
- platform: template
  sensors:
    uv_index_friendly:
      friendly_name: 'UV index'
      value_template: >-
        {% set index = (states('sensor.current_uv_index')) | int %}
        {% if index >= 11 %}
          Dangerous
        {% elif index >= 8 %}
          High risk
        {% elif index >= 6 %}
          Sunburn
        {% elif index >= 3 %}
          Sunglasses
        {% elif index >= 1 %}
          No risk
        {% elif index >= 0 %}
          No UV radiation
        {% elif index < 0 %}
          unknown
        {% endif %}
      icon_template: >-
        {% set index = (states('sensor.current_uv_index')) | int %}
        {% if index >= 11 %}
          mdi:close-octagon
        {% elif index >= 8 %}
          mdi:alert
        {% elif index >= 6 %}
          mdi:shield-sun
        {% elif index >= 3 %}
          mdi:sunglasses
        {% elif index >= 0 %}
          mdi:check-bold
        {% elif index < 0 %}
          mdi:eye
        {% endif %}
