###
# Component Counters
###
- platform: template
  sensors:
    count_entities:
      friendly_name: 'Entities'
      value_template: >-
        {{ states | count }}
      icon_template: mdi:format-list-bulleted-square
    count_automations:
      friendly_name: 'Automations'
      value_template: >-
        {{ states.automation | count }}
      icon_template: mdi:autorenew
    count_scripts:
      friendly_name: 'Scripts'
      value_template: >-
        {{ states.script | count }}
      icon_template: mdi:script-text-outline
    count_device_trackers:
      friendly_name: 'Device Trackers'
      value_template: >-
        {{ states.device_tracker | count }}
      icon_template: mdi:map-marker
    count_binary_sensors:
      friendly_name: 'Binary Sensors'
      value_template: >-
        {{ states.binary_sensor | count }}
      icon_template: mdi:unfold-more-horizontal
    count_sensors:
      friendly_name: 'Sensors'
      value_template: >-
        {{ states.sensor | count }}
      icon_template: mdi:resistor
    count_switches:
      friendly_name: 'Switches'
      value_template: >-
        {{ states.switch | count }}
      icon_template: mdi:light-switch
    count_zones:
      friendly_name: 'Zones'
      value_template: >-
        {{ states.zone | count }}
      icon_template: mdi:map-marker-radius
    count_input_booleans:
      friendly_name: 'Input Boolean'
      value_template: >-
        {{ states.input_boolean | list | count }}
      icon_template: mdi:toggle-switch
    count_input_selects:
      friendly_name: 'Input Select'
      value_template: >-
        {{ states.input_select | count }}
      icon_template: mdi:view-list
    count_input_datetimes:
      friendly_name: 'Date\Time'
      value_template: >-
        {{ states.input_datetime | count }}
      icon_template: mdi:timetable
    count_timers:
      friendly_name: 'Timers'
      value_template: >-
        {{ states.timer | count }}
      icon_template: mdi:timer-outline
    count_lights:
      friendly_name: 'Lights'
      value_template: >-
        {{ states.light | count }}
      icon_template: mdi:lightbulb-group
    count_climates:
      friendly_name: 'Climate'
      value_template: >-
        {{ states.climate | count }}
      icon_template: mdi:air-conditioner
