##############################################
#                   SENSORS                  #
##############################################
# Date and Time
- platform: time_date
  display_options:
    - time
    - date
    - date_time
    - time_date

# Seasons sensor
- platform: season

# Random Number
- platform: random
  name: Random Number
