# ###
#
# The seventeentrack sensor platform allows users to get package data tied to their 17track.net account.
# https://www.home-assistant.io/integrations/seventeentrack/
#
# ###

- platform: seventeentrack
  username: !secret 17track_user
  password: !secret 17track_passwd
