# TV tracking
- platform: history_stats
  name: 'Track TV usage'
  entity_id: binary_sensor.tv
  state: 'on'
  type: time
  start: >-
    {{ now().replace(hour=0).replace(minute=0).replace(second=0) }}
  end: >-
    {{ now() }}
- platform: template
  sensors:
    track_tv_usage_formatted:
      friendly_name: 'Formatted TV usage'
      value_template: >-
        {% set hours = states('sensor.track_tv_usage') | float %}
        {% set minutes = ((hours % 1) * 60) | int %}
        {% set hours = (hours - (hours % 1)) | int %}
        {{ '%02i.%02i'%(hours, minutes) }}
      icon_template: mdi:timetable

- platform: history_stats
  name: 'Track Netflix'
  entity_id: binary_sensor.netflix_on
  state: 'on'
  type: time
  start: >-
    {{ now().replace(hour=0).replace(minute=0).replace(second=0) }}
  end: >-
    {{ now() }}
- platform: template
  sensors:
    track_netflix_usage_formatted:
      friendly_name: 'Formatted Netflix usage'
      value_template: >-
        {% set hours = states('sensor.track_netflix') | float %}
        {% set minutes = ((hours % 1) * 60) | int %}
        {% set hours = (hours - (hours % 1)) | int %}
        {{ '%02i.%02i'%(hours, minutes) }}
      icon_template: mdi:timetable
