###
# VACUUM
# Xiaomi vacuum sensors
- platform: template
  sensors:
    vacuum_status:
      friendly_name: 'Status'
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'status') }}
      icon_template: >-
        {% set status =  states('vacuum.xiaomi_vacuum_cleaner', 'status')  %}
        {% if status == 'Charging' %}
          mdi:battery-charging
        {% elif status == 'Cleaning' %}
          mdi:move-resize
        {% elif status == 'Returning home' %}
          mdi:home-import-outline
        {% elif status == 'Idle' %}
          mdi:dots-horizontal
        {% elif status == 'Paused' %}
          mdi:pause-circle
        {% else %}
          mdi:help-circle
        {% endif %}
    vacuum_fan_speed:
      friendly_name: 'Fan Speed'
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'fan_speed') }}
      icon_template: mdi:fan
    vacuum_battery:
      friendly_name: 'Vacuum Battery'
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'battery_level') }}
      unit_of_measurement: '%'
      icon_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'battery_icon') }}
    vacuum_cleaning_time:
      friendly_name: 'Time of Last Cycle'
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'cleaning_time') }}
      icon_template: mdi:timer
      unit_of_measurement: 'min'
    vacuum_cleaned_area:
      friendly_name: 'Area of Last Cycle'
      unit_of_measurement: 'm²'
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'cleaned_area') }}
      icon_template: mdi:ruler
    vacuum_cleanmainbrush:
      friendly_name: 'Replace main brush'
      unit_of_measurement: 'h'
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'main_brush_left') }}
      icon_template: mdi:screwdriver
    vacuum_cleansidebrush:
      friendly_name: 'Replace side brush'
      unit_of_measurement: 'h'
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'side_brush_left') }}
      icon_template: mdi:screwdriver
    vacuum_cleanfilter:
      friendly_name: 'Replace filter'
      unit_of_measurement: 'h'
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'filter_left') }}
      icon_template: mdi:screwdriver
    vacuum_sensordirtyleft:
      friendly_name: 'Clean sensor'
      unit_of_measurement: 'h'
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'sensor_dirty_left') }}
      icon_template: mdi:broom
    vacuum_last_cleaned:
      friendly_name: 'Last cleaned'
      value_template: >-
          {{ as_timestamp(state_attr('vacuum.xiaomi_vacuum_cleaner', 'clean_stop')) | timestamp_custom("%A, %H:%M", true) }}
      icon_template: mdi:timetable
