###########################################
#               AUTOMATIONS               #
###########################################
###
#  UI
###
# Set theme on start-up
- alias: 'Set theme on start-up'
  id: 5b3806c0-2bcc-4bc8-b538-ce724c934817
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: frontend.set_theme
      data:
        name: noctis
    - service: input_select.select_option
      data:
        entity_id: input_select.theme_list
        option: Noctis
# Select theme manually
- alias: 'Select theme'
  id: 653bfb33-82f2-4b2d-9c9c-cb4e1087f8df
  trigger:
    platform: state
    entity_id: input_select.theme_list
  action:
    - service_template: >-
        {% if trigger.to_state.state == 'Noctis' %}
          script.set_noctis
        {% elif trigger.to_state.state == 'Synthwave' %}
          script.set_synthwave
        {% endif %}

###
# GLOBAL
###
# Turn-off movement detection at Shabat\Chag
- alias: 'Enable Shabat Mode at Shabat\Chag'
  id: 501ee07f-794c-4b49-ba18-5e21f111510c
  trigger:
    platform: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.shabat_mode
    - service: switch.turn_on
      entity_id: switch.shabat_mode
# Turn-on movement detection at Shabat\Chag end
- alias: 'Disable Shabat Mode at Shabat\Chag'
  id: 6b9bd845-cb16-4fb9-bad2-003aeb2b9363
  trigger:
    platform: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    to: 'off'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.shabat_mode
    - service: switch.turn_off
      entity_id: switch.shabat_mode

# Turn-off movement detection in multisensors at Shabat\Chag
- alias: 'Disable Multisensors Motion sensors'
  id: 011001b9-dfee-43fb-b635-9f3f1c81388a
  trigger:
    platform: state
    entity_id: switch.shabat_mode
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.shabat_select
# Turn-on movement detection in multisensors at Shabat\Chag end
- alias: 'Enable Multisensors Motion sensors'
  id: 2fcfe963-6207-4429-ad51-1656eaed14dd
  trigger:
    platform: state
    entity_id: switch.shabat_mode
    to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.shabat_select

### Shabat and Chag
- alias: 'Shabat and Chag Lighting'
  id: 66aff0fc-7022-4577-9d72-2f35104ca746
  trigger:
    platform: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    to: 'on'
  condition:
    - condition: state
      entity_id: group.person
      state: 'home'
  action:
    - service: script.turn_on
      entity_id: script.shabat_chag_lighting_sequence

- alias: 'Shabat and Chag Lighting off'
  id: 84dba792-958c-432e-bfb4-db8266bb3f0a
  trigger:
    platform: template
    value_template: >
      {{ states('sensor.time') == states('input_select.shabat_lights_off_time') }}
  condition:
    - condition: state
      entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.public_lights
        transition: 300

- alias: 'Shabat Morning lighting'
  id: 3ac9405a-dde0-41f2-850b-413cb15a708d
  trigger:
    platform: time
    at: '08:00:00'
  condition: # add condition based on light amount
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
          state: 'on'
        - condition: state
          entity_id: group.person
          state: 'home'
  action:
    - service: light.turn_on
      data:
        entity_id: light.public_lights
        transition: 120
        brightness_pct: 70

- alias: 'Shabat Morning Dining lighting'
  id: d2980177-8560-43f1-9fc4-26afd6406e73
  trigger:
    platform: time
    at: '09:30:00'
  condition: # add condition based on light amount
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
          state: 'on'
        - condition: state
          entity_id: group.person
          state: 'home'
  action:
    - service: light.turn_on
      data:
        entity_id: light.dining_lights
        transition: 60
        brightness_pct: 100

- alias: 'Shabat and Chag end lighting'
  id: 92ec94d8-89b9-4417-9c03-5711d20e5d32
  trigger:
    platform: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    to: 'off'
  condition:
    - condition: state
      entity_id: group.person
      state: 'home'
  action:
    - service: script.turn_on
      entity_id: script.shabat_chag_end_lighting_sequence

###
# KITCHEN
###
## Lights
# Turn on sink lights to max when someone in the kitchen
#- alias: 'Sink lights max brightness'
#  id: ec0d69d8-ec67-4146-81f1-de85066a37a7
#  trigger:
#    platform: state
#    to: 'on'
#    entity_id: sensor.kitchen_work_movement
#  condition:
#    - condition: state
#      entity_id: input_boolean.movement_detection
#      state: 'on'
#  action:
#    - service: light.turn_on
#      data:
#        entity_id: light.kitchen_work_light
#        brightness_pct: 100

###
# MASTER BEDROOM
###
## Lights
# Turn-off fairy lights at night
#- alias: 'turn off master-bedroom fairy lights at night'
#  id: 1a5b17ca-d49e-4ffb-b665-9fe4cd63d904
#  trigger:
#    platform: time
#    at: '23:00:00'
#  action:
#    - service: light.turn_off
#      entity_id: light.wled

### Lights
# Turn-off lights when away
- alias: 'Turn-off lights when away'
  id: c4219e30-3edb-4e1d-9621-eba64f593883
  trigger:
    platform: state
    entity_id: group.person
    to: 'not_home'
  action:
    - service: light.turn_off
      entity_id: light.all_lights

# Light-up in the morning
- alias: 'Turn on living room lights in workday morning-early'
  id: ab50f735-f05f-454e-813c-0ed8cdd4a51e
  trigger:
    platform: time
    at: '05:45:00'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: 'on'
        - condition: state
          entity_id: group.person
          state: 'home'
  action:
    - service: light.turn_on
      data:
        entity_id: light.living_room_lights
        kelvin: 2800
        brightness_pct: 30
        transition: 300
- alias: 'Turn on living room lights in workday morning-later'
  id: 3a42a962-7bf3-4952-b8a2-99591aa827f5
  trigger:
    platform: time
    at: '06:30:00'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: 'on'
        - condition: state
          entity_id: group.person
          state: 'home'
  action:
    - service: light.turn_on
      data:
        entity_id: light.living_room_lights
        kelvin: 4000
        brightness_pct: 100
        transition: 600

# Light-up master bedroom the morning
- alias: 'Turn on the master-bedroom lights in a workday morning'
  id: cb2d8573-74f4-440c-9b2e-23057b5e492c
  trigger:
    platform: time
    at: '06:45:00'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: 'on'
        - condition: state
          entity_id: group.person
          state: 'home'
  action:
    - service: light.turn_on
      data:
        entity_id: light.master_bedroom
        kelvin: 3000
        brightness_pct: 60
        transition: 600

# Light-up night lights on movement detection
- alias: 'Turn on lights when movement detected at night'
  id: bbe9c72e-6578-4fd1-b25c-12908145ac14
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.night
          state: 'on'
        - condition: state
          entity_id: 
            - binary_sensor.jewish_calendar_issur_melacha_in_effect
            - input_boolean.night_light_override
          state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom1
        kelvin: 3500
        brightness_pct: 1
    - service: timer.start
      entity_id: timer.motion_lights_night
- alias: 'Turn off lights when movement is not detected set minutes after triggered'
  id: 395fbb3d-01ec-477e-a5dc-aab76acef310
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.motion_lights_night
  action:
    - service: light.turn_off
      data:
        entity_id: light.bedroom1
        transition: 60