- alias: 'Turn off Living-Room AC at night'
  id: 5f250d83-aa9a-4e2a-af61-8ad83f39a75a
  trigger:
    platform: time
    at: '22:00:00'
  condition:
      - condition: state
        entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
        state:  'off'
  action:
    - service: climate.turn_off
      data:
        entity_id: climate.slvn

- alias: 'Turn on AC before arriving home'
  id: 4c8ce2bf-8e22-4959-8272-2faeb884cf8c
  trigger:
    platform: time
    at: '16:00:00'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.living_room_temperature_threshold
          state: 'off'
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: 'on'
        - condition: state
          entity_id: group.person
          state: 'not_home'
  action:
    - service: climate.turn_on
      data:
        entity_id: climate.slvn
- alias: 'Turn off AC if we did not arrived'
  id: ef558f55-51e6-4aaf-83db-72d066ad6826
  trigger:
    platform: time
    at: '16:45:00'
  condition:
    - condition: state
      entity_id: group.person
      state: 'not_home'
  action:
    - service: climate.turn_off
      data:
        entity_id: climate.slvn

- alias: 'Master bedroom AC night start'
  id: 830ce5bd-4949-4e8c-81f4-6363777ea9db
  trigger:
    - platform: time
      at: '19:00:00'
  condition:
    - condition: state
      entity_id: group.person
      state: 'home'
    - condition: state
      entity_id: binary_sensor.master_bedroom_temperature_threshold
      state: 'off'
  action:
    - service: climate.turn_on
      data:
        entity_id: climate.shynh
- alias: 'Master Bedroom AC night climate on'
  id: 4bbb5a20-5b66-4a7f-ac31-09bc5e90a85b
  trigger:
    - platform: state
      entity_id: binary_sensor.master_bedroom_temperature_threshold
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.person
        state: 'home'
      - condition: time
        after: '20:00:00'
        before: '07:00:00'
  action:
    - service: climate.turn_on
      data:
        entity_id: climate.shynh

- alias: 'Master bedroom AC shabbat morning start'
  id: 880cfa3e-b040-4e89-a04e-7832d2c28024
  trigger:
    - platform: time
      at: '12:00:00'
  condition:
    - condition: state
      entity_id: group.person
      state: 'home'
    - condition: state
      entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
      state: 'on'
  action:
    - service: climate.turn_on
      data:
        entity_id: climate.shynh
- alias: 'Master Bedroom AC shabbat climate on'
  id: bffd958d-fc77-4819-adaf-603273968eb7
  trigger:
    - platform: state
      entity_id: binary_sensor.master_bedroom_temperature_threshold
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.person
        state: 'home'
      - condition: time
        after: '07:00:00'
        before: '19:00:00'
      - condition: state
        entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
        state: 'on'
  action:
    - service: climate.turn_on
      data:
        entity_id: climate.shynh

- alias: 'Master Bedroom AC comfort climate off'
  id: 4149a58b-7c72-4403-abd8-c211fc4e2cec
  trigger:
    - platform: state
      entity_id: binary_sensor.master_bedroom_temperature_threshold
      from: 'off'
      to: 'on'
      for:
        minutes: 30
  action:
    - service: climate.turn_off
      entity_id: climate.shynh

- alias: 'Turn off Living-Room AC at night'
  id: c7396673-d257-4267-a72f-060ee4d43603
  trigger:
    platform: template
    value_template: >-
      {{ states('sensor.time') == states('input_select.shabat_lights_off_time') }}
  condition:
      - condition: state
        entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
        state:  'on'
  action:
    - service: climate.turn_off
      data:
        entity_id: climate.slvn

- alias: 'Turn on living room AC on shabbat if its hot'
  id: 7cc3353c-e1ba-4757-8d32-df0a9c853264
  trigger:
    - platform: time
      at: '09:00:00'
    - platform: time
      at: '15:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.person
        state: 'home'
      - condition: state
        entity_id: binary_sensor.living_room_temperature_threshold
        state: 'off'
      - condition: state
        entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
        state: 'on'
  action:
    - service: climate.turn_on
      data:
        entity_id: climate.slvn

- alias: 'Turn off Living room AC on shabbat noon'
  id: f570b89f-8ce5-4b09-9230-1acc55c54528
  trigger:
    - platform: time
      at: '12:00:00'
  condition:
    - condition: state
      entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
      state:  'on'
  action:
    - service: climate.turn_off
      data:
        entity_id: climate.slvn

- alias: 'Living room AC comfort climate off'
  id: b7be1e48-eb8f-4a24-a860-7af910766fc8
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_temperature_threshold
      from: 'off'
      to: 'on'
      for:
        minutes: 30
  action:
    - service: climate.turn_off
      entity_id: climate.slvn

- alias: 'Living room AC shabbat climate on'
  id: 292c2018-a4fc-406e-90af-69cc579a840c
  trigger:
    - platform: state
      entity_id: binary_sensor.master_bedroom_temperature_threshold
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.person
        state: 'home'
      - condition: state
        entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
        state:  'on'
      - condition: or
        conditions:
          - condition: time
            after: '09:00:00'
            before: '12:00:00'
          - condition: time
            after: '15:00:00'
            before: '19:00:00'
  action:
    - service: climate.turn_on
      data:
        entity_id: climate.slvn

- alias: 'Turn off all AC when shabbat ends'
  id: dcc2346f-99f5-4437-80d6-1183d28372c6
  trigger:
    - platform: state
      entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
      to: 'off'
  action:
    - service: climate.turn_off
      data:
        entity_id: climate.slvn
    - service: climate.turn_off
      data:
        entity_id: climate.shynh
