####
# Climate
###

- alias: 'Turn off Living-Room AC at night'
  id: 5f250d83-aa9a-4e2a-af61-8ad83f39a75a
  trigger:
    platform: time
    at: '22:00:00'
  condition:
      - condition: state
        entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
        state:  'off'
  action:
    - service: climate.turn_off
      data:
        entity_id: climate.slvn

- alias: 'Turn off Living-Room AC at Shabbat night'
  id: c7396673-d257-4267-a72f-060ee4d43603
  trigger:
    platform: template
    value_template: >-
      {{ states('sensor.time') == states('input_select.shabat_lights_off_time') }}
  condition:
      - condition: state
        entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
        state:  'on'
  action:
    - service: climate.turn_off
      data:
        entity_id: climate.slvn

- alias: 'Turn off Living room AC on shabbat noon'
  id: f570b89f-8ce5-4b09-9230-1acc55c54528
  trigger:
    - platform: time
      at: '12:00:00'
  condition:
    - condition: state
      entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
      state:  'on'
  action:
    - service: climate.turn_off
      data:
        entity_id: climate.slvn
