###
# Lights
###
# Turn-off lights when away
- alias: 'Turn-off lights when away'
  id: c4219e30-3edb-4e1d-9621-eba64f593883
  trigger:
    platform: state
    entity_id: group.person
    to: 'not_home'
  action:
    - service: light.turn_off
      entity_id: light.all_lights

###
# MASTER BEDROOM
###
# Light-up in the morning
- alias: 'Turn on living room lights in workday morning-early'
  id: ab50f735-f05f-454e-813c-0ed8cdd4a51e
  trigger:
    platform: time
    at: '05:45:00'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: 'on'
        - condition: state
          entity_id: group.person
          state: 'home'
  action:
    - service: light.turn_on
      data:
        entity_id: light.living_room_lights
        kelvin: 2800
        brightness_pct: 30
        transition: 300
- alias: 'Turn on living room lights in workday morning-later'
  id: 3a42a962-7bf3-4952-b8a2-99591aa827f5
  trigger:
    platform: time
    at: '06:30:00'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: 'on'
        - condition: state
          entity_id: group.person
          state: 'home'
  action:
    - service: light.turn_on
      data:
        entity_id: light.living_room_lights
        kelvin: 4000
        brightness_pct: 100
        transition: 600

# Light-up master bedroom the morning
- alias: 'Turn on the master-bedroom lights in a workday morning'
  id: cb2d8573-74f4-440c-9b2e-23057b5e492c
  trigger:
    platform: time
    at: '06:45:00'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: 'on'
        - condition: state
          entity_id: group.person
          state: 'home'
  action:
    - service: light.turn_on
      data:
        entity_id: light.master_bedroom
        kelvin: 3000
        brightness_pct: 60
        transition: 600

###
# Motion
###
# Light-up night lights on movement detection
- alias: 'Turn on lights when movement detected at night'
  id: bbe9c72e-6578-4fd1-b25c-12908145ac14
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.night
          state: 'on'
        - condition: state
          entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
          state: 'off'
        - condition: state
          entity_id: input_boolean.night_light_override
          state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom1
        kelvin: 3600
        brightness_pct: 2
# Start the lights timer after no movement detected
- alias: 'Start the lights timer'
  id: 2c73b4e0-34cc-4cfd-984e-159f321faa64
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'off'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.night
          state: 'on'
        - condition: state
          entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
          state: 'off'
        - condition: state
          entity_id: input_boolean.night_light_override
          state: 'on'
  action:
    - service: timer.start
      data:
        entity_id: timer.motion_lights_night
# Turn off the lights when the timer ends
- alias: 'Turn off lights when the timer is finished'
  id: 395fbb3d-01ec-477e-a5dc-aab76acef310
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.motion_lights_night
  condition:
    - condition: state
      entity_id: input_boolean.night_light_override
      state: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.bedroom1
        transition: 30
