###
# Shabat notifications
###
- alias: 'Notify for Salatim'
  id: c5553611-fb7b-42d7-80af-2608a31c2c25
  trigger:
    platform: state
    entity_id: binary_sensor.shabat_notification_trigger_30m
    to: 'on'
  condition:
    - condition: time
      weekday:
        - fri
  action:
    - service: notify.mobile_app_mi_9t
      data:
        title: 'שבת שלום!'
        message: 'זכרת להכין מיחם, חציל וסלטים אחרים?'
- alias: 'Notify for Shabat'
  id: 1145acf8-55b2-4564-bab8-94090f75d7d5
  trigger:
    platform: state
    entity_id: binary_sensor.shabat_notification_trigger_10m
    to: 'on'
  condition:
    - condition: time
      weekday:
        - fri
  action:
    - service: notify.mobile_app_mi_9t
      data:
        title: 'שבת שלום!'
        message: 'שבת נכנסת בעוד 10 דקות.'
    - service: notify.mobile_app_redmi_note_7
      data:
        title: 'שבת שלום!'
        message: 'שבת נכנסת בעוד 10 דקות.'
