###
# Shabat mode
###
# Enters Shabat mode on Shabat\Chag
- alias: 'Enable Shabat Mode at Shabat\Chag'
  id: 501ee07f-794c-4b49-ba18-5e21f111510c
  trigger:
    platform: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.shabat_mode
# Exits Shabat mode on Shabat\Chag end
- alias: 'Disable Shabat Mode at Shabat\Chag'
  id: 6b9bd845-cb16-4fb9-bad2-003aeb2b9363
  trigger:
    platform: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.shabat_mode
