###
#  UI
###
# Set theme on start-up
- alias: 'Set theme on start-up'
  id: 5b3806c0-2bcc-4bc8-b538-ce724c934817
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: frontend.set_theme
      data:
        name: noctis
    - service: input_select.select_option
      data:
        entity_id: input_select.theme_list
        option: Noctis
# Select theme manually
- alias: 'Select theme'
  id: 653bfb33-82f2-4b2d-9c9c-cb4e1087f8df
  trigger:
    platform: state
    entity_id: input_select.theme_list
  action:
    - service_template: >-
        {% if trigger.to_state.state == 'Noctis' %}
          script.set_noctis
        {% elif trigger.to_state.state == 'Synthwave' %}
          script.set_synthwave
        {% endif %}
