###
# History settings
###

exclude:
  entities:
    - sensor.uptime_friendly
    - sensor.dnsip
    - sensor.season
    - sensor.track_steam_playtime
    - sensor.israel_weather_forecast
    - sensor.myip
    - sensor.ims_daily
  entity_globs:
    - binary_sensor.*_notification_trigger
    - sensor.jewish_calendar_*
    - sensor.count_*
    - sensor.mfc_*
    - sensor.brother_mfc_*
    - sensor.skin_type_*
    - sensor.*_formatted
  domains:
    - camera
    - automation
    - updater
    - sun
    - script
    - switch
