---

exclude:
  entities:
    - sensor.uptime_friendly
    - sensor.dnsip
    - sensor.season
    - sensor.track_steam_playtime
    - sensor.israel_weather_forecast
    - sensor.myip
    - sensor.ims_daily
    - sensor.hacs
  entity_globs:
    - sensor.jewish_calendar_*
    - sensor.count_*
    - sensor.skin_type_*
    - sensor.*_formatted

    - binary_sensor.*_notification_trigger
    - binary_sensor.is_*
  domains:
    - camera
    - automation
    - updater
    - sun
    - script
    - switch
    - timer
