###
# Logbook settings
###
exclude:
  entities:
    - binary_sensor.day
    - binary_sensor.night
    - sensor.uptime_friendly
    - sensor.dnsip
    - binary_sensor.random_boolean
    - sensor.random_number
    - sensor.track_tv_usage_formatted
    - sensor.track_steam_playtime
    - sensor.track_steam_playtime_formatted
    - binary_sensor.steam_game_on
    - sensor.season
    - sensor.israel_weather_forecast
    - sensor.local_ip
  entity_globs:
    - sensor.openweathermap_*
    - sensor.jewish_calendar_*
    - sensor.count_*
    - sensor.mfc_*
  domains:
    - updater
    - sun
    - script
