###
# Recorder settings
###

db_url: !secret postgres_addr
purge_keep_days: 7
commit_interval: 0
exclude:
  entities:
    - sensor.time
    - sensor.date
    - sensor.date_time
    - sensor.season
    - sensor.israel_weather_forecast
    - sensor.myip
    - sensor.ims_daily
    - sensor.openweathermap_forecast_time
  entity_globs:
    - sensor.count_*
    - sensor.mfc_*
    - sensor.brother_mfc_*
    - sensor.skin_type_*
  domains:
    - sun
    - weather
    - updater
