###
# Recorder settings
###

db_url: !secret postgres_addr
purge_keep_days: 7
commit_interval: 1 # to be changed later to 0
exclude:
  entities:
    - sensor.time
    - sensor.date
    - sensor.date_time
    - sensor.season
    - sensor.israel_weather_forecast
    - sensor.local_ip
  entity_globs:
    - sensor.count_*
    - sensor.seventeentrack_*
    - sensor.mfc_*
    - sensor.skin_type_*
  domains:
    - sun
    - weather
    - updater
