###########################################################
#                        Bathroom                         #
###########################################################
substitutions:
  devicename: bathroom_multisensor
  upper_devicename: "Bathroom"
  template_id: bathroom

esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret ssid
  password: !secret wifi_passwd
  manual_ip:
    static_ip: 10.0.0.73
    gateway: !secret gateway
    subnet: 255.255.255.0
  ap:
    ssid: "${upper_devicename}_fallback_hotspot"
    password: !secret ap_passwd

captive_portal:
logger:
api:
ota:

i2c:
  sda: D2
  scl: D1
  scan: True

mcp23008:
  - id: mcp23017_hub
    address: 0x20

binary_sensor:
  - platform: gpio
    pin:
      number: D6
    name: "${upper_devicename} Motion"
    device_class: motion
    filters:
      - delayed_on: 1500ms
      - delayed_off: 30s
  - platform: gpio
    name: "${upper_devicename} Door"
    device_class: door
    pin:
      mcp23008: mcp23017_hub
      number: 1
      mode: INPUT
#      inverted: false
  - platform: status
    name: "${upper_devicename}"

sensor:
  - platform: bme280
    temperature:
      name: "${upper_devicename} Temperature"
      id: ${template_id}_temperature
      oversampling: 16x
    pressure:
      name: "${upper_devicename} Pressure"
    humidity:
      name: "${upper_devicename} Humidity"
      id: ${template_id}_humidity
    address: 0x76
    update_interval: 60s
  - platform: template
    name: "${upper_devicename} Dew Point"
    lambda: |-
      return (243.5 * (log(id(${template_id}_humidity).state/100) + ((17.67 * id(${template_id}_temperature).state) /
      (243.5 + id(${template_id}_temperature).state))) /
      (17.67 - log(id(${template_id}_humidity).state/100) - ((17.67 * id(${template_id}_temperature).state) /
      (243.5 + id(${template_id}_temperature).state))));
    unit_of_measurement: '°C'
    icon: mdi:water
  - platform: bh1750
    name: "${upper_devicename} Illuminance"
    address: 0x23
    measurement_time: 69
    update_interval: 60s

text_sensor:
  - platform: template
    name: "${upper_devicename} Humidity Range"
    lambda: |-
      if (id(${template_id}_humidity).state > 80) {
        return {"Very Humid"};
      } else if (id(${template_id}_humidity).state > 65) {
        return {"Humid"};
      } else if (id(${template_id}_humidity).state < 40) {
        return {"Dry"};
      } else {
        return {"Comfortable"};
      }
    update_interval: 60s
    icon: mdi:water-percent

switch:
  - platform: restart
    name: "Restart ${upper_devicename}"
  - platform: gpio
    name: "${upper_devicename} Shabat Select"
    pin:
      number: D5
      inverted: yes
