############################################################
#                        Shabat Plate                      #
############################################################
substitutions:
  devicename: car_remote
  upper_devicename: Car Remote

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret ssid
  password: !secret wifi_pass
  manual_ip:
    static_ip: 10.0.0.80
    gateway: 10.0.0.138
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename}
    password: !secret ap_pass
# Enable backup AP
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable OTA Updates
ota:

# Code
sensor:
  # WiFi sensor
  - platform: wifi_signal
    name: ${upper_devicename} WiFi reception
    update_interval: 60s

binary_sensor:
  - platform: status
    name: ${upper_devicename} Connection

switch:
  - platform: gpio
    pin: GPIO10
    id: toggle
  - platform: template
    name: "Open/Close"
    icon: mdi:car-door-lock
    turn_on_action:
    - switch.turn_on: toggle
    - delay: 500ms
    - switch.turn_off: toggle
  - platform: restart
    name: Restart ${upper_devicename}
