####################################################
#                      BATHROOM                    #
####################################################
id: bathroom
title: "Bathroom"
icon: mdi:shower
cards:
  - type: custom:decluttering-card
    template: room_data
    variables:
      - room: bathroom

  - type: entities
    entities:
      - sensor.bathroom_mold_indicator
