####################################################
#                    EXTRA STUFF                   #
####################################################
id: extra_stuff
title: "Extra Stuff"
icon: mdi:information-outline
cards:
  - type: entities
    entities:
      - type: custom:hui-element
        card_type: picture
        image: 'https://brands.home-assistant.io/seventeentrack/logo.png'
      - type: custom:hui-element
        card_type: glance
        entities:
          - entity: sensor.seventeentrack_packages_not_found
            name: "Not-Found"
          - entity: sensor.seventeentrack_packages_in_transit
            name: "In-Transit"
          - entity: sensor.seventeentrack_packages_ready_to_be_picked_up
            name: "Ready to be Picked-Up"
      - type: custom:auto-entities
        card:
          type: entities
          title: "Package List"
          show_header_toggle: false
        filter:
          include:
            - entity_id: 'sensor.seventeentrack_package_*'
