####################################################
#                    Home Office                   #
####################################################
id: work_room
title: 'Home Office'
icon: mdi:desk
background: 'var(--background-image)'
cards:
  - type: entities
    title: 'Printer'
    entities:
      - sensor.brother_mfc_j4410dw
      - binary_sensor.printer
      - type: custom:bar-card
        entity_row: true
        positions:
          indicator: 'off'
          icon: 'off'
        columns: 4
        height: '150px'
        entities:
          - name: 'Cyan'
            color: "cyan"
            direction: up
            entity: sensor.brother_mfc_j4410dw_cyan_ink_cartridge
          - name: 'Magenta'
            color: "magenta"
            direction: up
            entity: sensor.brother_mfc_j4410dw_magenta_ink_cartridge
          - name: 'Yellow'
            color: "yellow"
            direction: up
            entity: sensor.brother_mfc_j4410dw_yellow_ink_cartridge
          - name: 'Black'
            color: "black"
            direction: up
            entity: sensor.brother_mfc_j4410dw_black_ink_cartridge

  - type: entities
    entities:
      - sensor.steam_76561198173612681
      - sensor.steam_game
      - type: custom:hui-element
        card_type: custom:mini-graph-card
        entities:
          - entity: sensor.track_steam_playtime_formatted
            unit: hours
            name: 'Steam playtime'
        show:
          graph: bar
          labels: false
        hours_to_show: 168
        group_by: date
        color_thresholds:
          - value: 1
            color: "#29A797"
          - value: 2
            color: "#F19631"
          - value: 3
            color: "#D2212A"
