---

id: monitoring
title: "Monitoring"
icon: mdi:chart-areaspline
cards:
  - type: custom:animated-consumption-card
    entity: sensor.total_ac_power_consumption

  - type: custom:mini-graph-card
    name: "AC Power Consumption"
    unit: 'kW'
    hours_to_show: 750
    line_width: 1
    entities:
      - entity: sensor.total_ac_energy_usage_daily
        name: "Daily"
        color: '#04FC04'
        show_state: true
        show_points: false
      - entity: sensor.total_ac_energy_usage_weekly
        name: "Weekly"
        color: 'yellow'
        show_state: false
        show_points: false
      - entity: sensor.total_ac_energy_usage_monthly
        name: "Monthly"
        color: 'red'
        show_state: false
        show_points: false
    show:
      fill: fade

  - type: custom:apexcharts-card
    graph_span: 30d
    span:
      end: day
    header:
      show: true
      title: "Daily water consumption"
    apex_config:
      chart:
        type: area
        height: 200
      stroke:
        show: true
        width: 1
        curve: smooth
      legend:
        show: false
      dataLabels:
        enabled: true
      fill:
        type: gradient
        gradient:
          shadeIntensity: 0.1
          opacityFrom: 0.25
          opacityTo: 1
          inverseColors: true
          stops:
            - 0
            - 90
            - 100
    series:
      - color: '#74A4F4'
        entity: sensor.water_meter_9926387_today_s_consumption
        type: column
        group_by:
          func: max
          duration: 24h
