---

id: overview
title: "Overview"
cards:
  - type: horizontal-stack
    cards:
      - type: picture-elements
        image: '/local/assets/yuval.jpg'
        elements:
          - type: state-label
            entity: sensor.yuval_battery_level
            style:
              top: 11%
              right: '-2%'
          - type: state-icon
            entity: sensor.yuval_battery_level
            style:
              top: 10%
              right: '-10%'
          - type: conditional
            conditions:
              - entity: binary_sensor.workday_sensor
                state: 'on'
              - entity: person.yuval
                state: 'home'
            elements:
              - type: state-icon
                entity: sensor.yuval_from_home_to_work
                icon: mdi:home-export-outline
                style:
                  top: 60%
                  right: '-1%'
                  '--paper-item-icon-color': white
                  transform: scale(0.8)
              - type: state-label
                entity: sensor.yuval_from_home_to_work
                style:
                  top: 68.5%
                  right: '-1%'
                  weight: 50px
                  color: white
                  font-weight: 300
                  font-size: 12px
          - type: conditional
            conditions:
              - entity: binary_sensor.workday_sensor
                state: 'on'
              - entity: person.yuval
                state: 'not_home'
            elements:
              - type: state-icon
                entity: sensor.yuval_from_work_to_home
                icon: mdi:home-export-outline
                style:
                  top: 60%
                  right: '-1%'
                  '--paper-item-icon-color': white
                  transform: scale(0.8)
              - type: state-label
                entity: sensor.yuval_from_work_to_home
                style:
                  top: 68.5%
                  right: '-1%'
                  weight: 50px
                  color: white
                  font-weight: 300
                  font-size: 12px
          - type: state-label
            entity: sensor.yuval_geocoded_location
            attribute: Thoroughfare
            style:
              bottom: '8%'
              right: '-18%'
              weight: 200px
              color: white
              font-weight: 300
              font-size: 16px
          - type: state-label
            entity: sensor.yuval_geocoded_location
            attribute: Locality
            style:
              bottom: '3%'
              right: '-12.5%'
              weight: 200px
              color: white
              font-weight: 300
              font-size: 12px
      - type: picture-elements
        image: '/local/assets/tohar.jpg'
        elements:
          - type: state-label
            entity: sensor.tohar_battery_level
            style:
              top: 11%
              right: '-2%'
          - type: state-icon
            entity: sensor.tohar_battery_level
            style:
              top: 10%
              right: '-10%'
          - type: state-label
            entity: sensor.tohar_geocoded_location
            attribute: Thoroughfare
            style:
              bottom: '8%'
              right: '-18%'
              weight: 200px
              color: white
              font-weight: 300
              font-size: 16px
          - type: state-label
            entity: sensor.tohar_geocoded_location
            attribute: Locality
            style:
              bottom: '3%'
              right: '-12.5%'
              weight: 200px
              color: white
              font-weight: 300
              font-size: 12px

  - type: entities
    title: "זמני היום"
    show_header_toggle: false
    entities:
      - entity: sensor.jewish_calendar_date
        name: "תאריך"
      - entity: binary_sensor.is_fast_day
        type: conditional
        conditions:
          - entity: binary_sensor.is_fast_day
            state: 'on'
        row:
          entity: binary_sensor.is_fast_day
      - entity: sensor.jewish_calendar_day_of_the_omer
        type: conditional
        conditions:
          - entity: binary_sensor.is_omer
            state: 'on'
        row:
          entity: sensor.jewish_calendar_day_of_the_omer
          name: "ספירת העומר"
      - type: divider
      - entity: sensor.jewish_calendar_parshat_hashavua
        name: "פרשת השבוע"
      - entity: sensor.jewish_calendar_upcoming_candle_lighting
        type: custom:multiple-entity-row
        name: "הדלקת נרות"
        format: relative
        entities:
          - entity: sensor.jewish_calendar_upcoming_candle_lighting
            format: time
            name: false
      - entity: sensor.jewish_calendar_upcoming_havdalah
        type: custom:multiple-entity-row
        name: "הבדלה"
        format: relative
        entities:
          - entity: sensor.jewish_calendar_upcoming_havdalah
            format: time
            name: false
      - type: divider
      - entity: sensor.jewish_calendar_daf_yomi
        name: "דף יומי"

  - type: entities
    entities:
      - type: custom:weather-card
        entity: weather.openweathermap
        current: true
        details: true
        hourly_forecast: true
        number_of_forecasts: 5
      - type: custom:hui-element
        card_type: markdown
        content: >-
          {{
            states.sensor.israel_weather_forecast.attributes.entries[0].summary
          }}
      - type: custom:hui-element
        card_type: horizontal-stack
        cards:
          - type: glance
            entities:
              - entity: sensor.wind_scale_friendly
          - type: glance
            entities:
              - entity: sensor.uv_index_friendly
          - type: custom:compass-card
            indicator_sensors:
              - sensor: sensor.openweathermap_wind_bearing
            value_sensors:
              - sensor: sensor.openweathermap_wind_speed
      - type: custom:air-visual-card
        hide_title: true
        air_pollution_level: sensor.u_s_air_pollution_level
        air_quality_index: sensor.u_s_air_quality_index
        main_pollutant: sensor.u_s_main_pollutant

  - type: custom:mini-media-player
    entity: media_player.googlehome3668
    group: false
    tts:
      platform: microsoft
    hide:
      progress: true
    shortcuts:
      columns: 2
      buttons:
        - name: "Galatz"
          type: script
          id: script.play_radio_stream
          data:
            entity_id: media_player.googlehome3668
            content_id: Galei Zahal
        - name: "Galgalatz"
          type: script
          id: script.play_radio_stream
          data:
            entity_id: media_player.googlehome3668
            content_id: GLGLZ

  - type: conditional
    conditions:
      - entity: binary_sensor.is_friday
        state: 'on'
    card:
      type: entities
      title: "פיקוד שבת"
      show_header_toggle: false
      entities:
        - switch.shabbat_mode
        - switch.shabbat_plate
        - type: custom:time-picker-card
          entity: input_datetime.shabbat_lights_off_time
          link_values: true
          minute_step: 30
          layout:
            name: inside
            align_controls: right

  - type: entities
    show_header_toggle: false
    entities:
      - switch.night_light_override
      - switch.disable_auto_clean
      - switch.kettle

  - type: custom:auto-entities
    card:
      type: entities
      title: "Active Lights"
      show_header_toggle: false
    show_empty: false
    filter:
      include:
        - domain: light
          state: 'on'
        - domain: light
          state: 'unavailable'
      exclude:
        - entity_id: '*lights'
