####################################################
#                     MAIN VIEW                    #
####################################################
id: overview
title: "Overview"
cards:
  - type: horizontal-stack
    cards:
      - type: entities
        entities:
          - type: custom:hui-element
            card_type: picture-entity
            image: '/local/assets/yuval.jpg'
            entity: person.yuval
#          - entity: sensor.yuval_geocoded_location
#            name: "Location"
          - entity: sensor.yuval_battery_level
            name: "Phone Battery"
      - type: entities
        entities:
          - type: custom:hui-element
            card_type: picture-entity
            image: '/local/assets/tohar.jpg'
            entity: person.tohar
#          - entity: sensor.tohar_geocoded_location
#            name: "Location"
          - entity: sensor.tohar_battery_level
            name: "Phone Battery"

  - type: entities
    entities:
      - type: custom:weather-card
        entity: weather.openweathermap
        current: true
        details: true
        hourly_forecast: true
        number_of_forecasts: 5
      - type: custom:hui-element
        card_type: markdown
        content: >-
          {{
            states.sensor.israel_weather_forecast.attributes.entries[0].summary
          }}
      - type: custom:hui-element
        card_type: horizontal-stack
        cards:
          - type: custom:hui-element
            card_type: glance
            entities:
              - entity: sensor.wind_scale_friendly
          - type: custom:hui-element
            card_type: glance
            entities:
              - entity: sensor.uv_index_friendly
          - type: custom:hui-element
            card_type: custom:compass-card
            indicator_sensors:
              - sensor: sensor.openweathermap_wind_bearing
            value_sensors:
              - sensor: sensor.openweathermap_wind_speed
      - type: custom:air-visual-card
        hide_title: true
        air_pollution_level: sensor.u_s_air_pollution_level
        air_quality_index: sensor.u_s_air_quality_index
        main_pollutant: sensor.u_s_main_pollutant

  - type: custom:animated-consumption-card
    entity: sensor.total_ac_power_consumption

  - type: entities
    title: "זמני היום"
    show_header_toggle: false
    entities:
      - entity: sensor.jewish_calendar_date
        name: "תאריך"
      - entity: binary_sensor.is_fast_day
        type: conditional
        conditions:
          - entity: binary_sensor.is_fast_day
            state: 'on'
        row:
          entity: binary_sensor.is_fast_day
      - entity: sensor.jewish_calendar_day_of_the_omer
        type: conditional
        conditions:
          - entity: binary_sensor.is_omer
            state: 'on'
        row:
          entity: sensor.jewish_calendar_day_of_the_omer
          name: "ספירת העומר"
      - type: divider
      - entity: sensor.jewish_calendar_parshat_hashavua
        name: "פרשת השבוע"
      - entity: sensor.jewish_calendar_upcoming_candle_lighting
        type: custom:multiple-entity-row
        name: "הדלקת נרות"
        format: relative
        entities:
          - entity: sensor.jewish_calendar_upcoming_candle_lighting
            format: time
            name: false
      - entity: sensor.jewish_calendar_upcoming_havdalah
        type: custom:multiple-entity-row
        name: "הבדלה"
        format: relative
        entities:
          - entity: sensor.jewish_calendar_upcoming_havdalah
            format: time
            name: false
      - type: divider
      - entity: sensor.jewish_calendar_daf_yomi
        name: "דף יומי"

  - type: entities
    title: "תאורת שבת"
    show_header_toggle: false
    entities:
      - switch.shabbat_mode
      - input_select.shabbat_lights_off_time

  - type: entities
    show_header_toggle: false
    entities:
      - switch.night_light_override
      - switch.disable_auto_clean

  - type: custom:auto-entities
    card:
      type: entities
      title: "Active Lights"
      show_header_toggle: false
    show_empty: false
    filter:
      include:
        - domain: light
          state: 'on'
        - domain: light
          state: 'unavailable'
      exclude:
        - entity_id: '*lights'
