---

id: statistics
title: "Statistics"
icon: mdi:chart-areaspline
cards:
  - type: custom:mini-graph-card
    name: "Temperature"
    hours_to_show: 84
    entities:
      - entity: sensor.living_room_temperature
        show_points: false
      - entity: sensor.master_bedroom_sensibo_temperature
        show_points: false
      - entity: sensor.bathroom_temperature
        show_points: false
      - entity: sensor.outside_temps
        name: "Outside"
        show_points: false
        color: 'white'
        show_fill: false
      - !include ../resources/graph_card_day_num.yaml
    show:
      fill: fade
      state: false
      labels: true
      labels_secondary: false
      points: false
    line_width: 2
    color_thresholds: !include ../resources/graph_card_temperature_thresholds.yaml

  - type: custom:mini-graph-card
    name: "Motion last 3 Hours"
    icon: mdi:motion-sensor
    hours_to_show: 3
    points_per_hour: 60
    update_interval: 30
    aggregate_func: max
    line_width: 2
    smoothing: false
    entities:
      - entity: binary_sensor.living_room_motion
        show_points: false
        color: '#7FB1CF'
      - entity: binary_sensor.bathroom_motion
        show_points: false
        color: '#C4BAB0'
      - !include ../resources/graph_card_day_bool.yaml
    state_map:
      - value: 'off'
        label: "Clear"
      - value: 'on'
        label: "Detected"
    show:
      fill: fade

  - type: custom:mini-graph-card
    name: "Lights"
    icon: mdi:lightbulb-on
    points_per_hour: 60
    hours_to_show: 12
    aggregate_func: max
    line_width: 2
    smoothing: false
    entities:
      - entity: binary_sensor.living_room_light_is_on
        show_points: false
        color: '#7FB1CF'
      - entity: binary_sensor.master_bedroom_light_is_on
        show_points: false
        color: '#A886F7'
      - !include ../resources/graph_card_day_bool.yaml
    state_map:
      - value: 'off'
        label: "כבוי"
      - value: 'on'
        label: "דולק"
    show:
      fill: fade
      labels: false

  - type: custom:mini-graph-card
    name: "Illumination"
    points_per_hour: 6
    entities:
      - entity: sensor.living_room_illuminance
        show_points: false
        color: '#7FB1CF'
      - entity: sensor.bathroom_illuminance
        show_points: false
        color: '#C4BAB0'
      - !include ../resources/graph_card_day_num.yaml
    show:
      fill: fade
      state: false
      labels: true
      labels_secondary: false
      points: false
    line_width: 2

  - type: custom:mini-graph-card
    name: "AC"
    icon: mdi:air-conditioner
    points_per_hour: 60
    hours_to_show: 12
    aggregate_func: max
    line_width: 2
    smoothing: false
    entities:
      - entity: binary_sensor.living_room_ac_is_on
        show_points: false
        color: '#7FB1CF'
      - entity: binary_sensor.master_bedroom_ac_is_on
        show_points: false
        color: '#A886F7'
      - !include ../resources/graph_card_day_bool.yaml
    state_map:
      - value: 'off'
        label: "כבוי"
      - value: 'on'
        label: "דולק"
    show:
      fill: fade
      labels: false

  - type: entities
    entities:
      - entity: media_player.mibox3
      - entity: sensor.track_tv_watch_time
        format: total
      - entity: sensor.track_netflix_watch_time
        format: total
      - entity: sensor.track_youtube_watch_time
        format: total

  - type: custom:mini-graph-card
    name: "AC Power Consumption"
    unit: 'kW'
    hours_to_show: 750
    line_width: 1
    entities:
      - entity: sensor.total_ac_energy_usage_daily
        name: "Daily"
        color: '#04FC04'
        show_state: true
        show_points: false
      - entity: sensor.total_ac_energy_usage_weekly
        name: "Weekly"
        color: 'yellow'
        show_state: false
        show_points: false
      - entity: sensor.total_ac_energy_usage_monthly
        name: "Monthly"
        color: 'red'
        show_state: false
        show_points: false
    show:
      fill: fade

  - type: custom:mini-graph-card
    name: "Water Consumption"
    unit: 'm³'
    icon: mdi:water-pump
    hours_to_show: 750
    group_by: date
    line_width: 1
    upper_bound: ~0.4
    entities:
      - entity: sensor.water_meter_9926387_monthly_consumption
        name: "Monthly consumption"
        show_graph: false
      - entity: sensor.water_meter_9926387_today_s_consumption
        name: "Today"
        color: '#74A4F4'
    show:
      graph: bar
      fill: fade
