####################################################
#                     UTILITIES                    #
####################################################
id: utilities
title: "System Monitor"
icon: mdi:server
cards:
  - type: entities
    entities:
      - type: custom:hui-element
        card_type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            icon: mdi:download-network
            font_size: 80
            entities:
              - entity: sensor.speedtest_download
                name: "Download"
            show:
              points: false
              fill: fade
          - type: custom:mini-graph-card
            icon: mdi:upload-network
            font_size: 80
            entities:
              - entity: sensor.speedtest_upload
                name: "Upload"
            show:
              fill: fade
              points: false
      - entity: sensor.myip
        name: "DNS IP"

  - type: glance
    title: "Components"
    columns: 4
    entities:
      - entity: sensor.count_entities
        name: "Entities"
      - entity: sensor.count_sensors
        name: "Sensors"
      - entity: sensor.count_binary_sensors
        name: "Binary Sensors"
      - entity: sensor.count_switches
        name: "Switches"
      - entity: sensor.count_lights
        name: "Lights"
      - entity: sensor.count_automations
        name: "Automations"
        tap_action:
          action: call-service
          service: automation.reload
      - entity: sensor.count_scripts
        name: "Scripts"
        tap_action:
          action: call-service
          service: script.reload
      - entity: sensor.count_zones
        name: "Zones"
        tap_action:
          action: call-service
          service: zone.reload
      - entity: sensor.count_device_trackers
        name: "Device Trackers"
      - entity: sensor.count_input_booleans
        name: "Input Booleans"
        tap_action:
          action: call-service
          service: input_boolean.reload
      - entity: sensor.count_input_selects
        name: "Input Select"
        tap_action:
          action: call-service
          service: input_select.reload
      - entity: sensor.count_input_datetimes
        name: "Input Date Times"
        tap_action:
          action: call-service
          service: input_datetime.reload
      - entity: sensor.count_timers
        name: "Timers"
        tap_action:
          action: call-service
          service: timer.reload
      - entity: sensor.count_climates
        name: "Climate"

  - type: entities
    entities:
      - type: custom:hui-element
        card_type: picture-entity
        image: 'https://repository-images.githubusercontent.com/12888993/0f9eb780-655b-11e9-85cb-0d3956096fe5'
        entity: sensor.current_version
      - entity: sensor.uptime
      - entity: script.homeassistant_restart
        icon: mdi:restart
      - type: custom:decluttering-card
        template: system_monitor
        variables:
          - cpu_usage: processor_use_percent
          - cpu_temps: processor_temperature
          - ram_usage: memory_use_percent
      - type: custom:bar-card
        entities:
          - entity: sensor.disk_use_percent
            name: "SD Storage"
            severity:
              - color: '#FF0F00'
                from: 91
                to: 100
      - type: custom:hui-element
        card_type: custom:mini-graph-card
        icon: mdi:database
        entities:
          - entity: sensor.db_size
            name: 'Database'
        show:
          fill: fade
          points: false
      - type: custom:hui-element
        card_type: entities
        entities:
          - script.reload_cli_sensors
          - script.reload_thermostats
          - script.reload_history_stats
          - script.reload_persons
          - script.reload_ping_sensors
          - script.reload_pyscript
          - script.reload_templates
          - script.reload_lovelace_resources
          - script.reload_themes

  - type: entities
    entities:
      - type: custom:hui-element
        card_type: picture-entity
        image: 'https://cdn.27.ua/main/14e/eaton_logo_mobile.png.pagespeed.ce.b32eoh_8jo.png'
        entity: sensor.ups_status
      - type: custom:battery-entity-row
        entity: sensor.ups_battery_charge
        name: 'Battery Charge'
      - type: custom:bar-card
        entity: sensor.ups_load
        name: 'Load'
        animation:
          state: 'on'
          speed: 2
        positions:
          indicator: 'off'
      - sensor.ups_input_voltage
      - sensor.ups_output_voltage

  - type: entities
    entities:
      - type: custom:hui-element
        card_type: picture
        image: 'https://leeselectronic.com/c/3280-category_default/nano-pi.jpg'
      - type: custom:decluttering-card
        template: system_monitor
        variables:
          - cpu_usage: npn2_cpu_used
          - cpu_temps: npn2_cpu_thermal_1_temperature
          - ram_usage: npn2_ram_used_percent
      - type: custom:bar-card
        entities:
          - entity: sensor.npn2_used_percent
            name: "SD Storage"
            severity:
              - color: '#FF0F00'
                from: 91
                to: 100
      - type: custom:hui-element
        card_type: entities
        entities:
          - type: custom:hui-element
            card_type: picture
            image: 'https://pi-hole.net/wp-content/uploads/2018/12/pihole-text-logo-white.png'
            tap_action:
              action: url
              url_path: 'http://10.0.0.6/admin/index.php'
          - sensor.pihole_status
          - entity: sensor.pi_hole_ads_percentage_blocked_today
            name: "Blocked Today"
          - entity: sensor.pi_hole_domains_blocked
            name: "Domains on Blocklist"
          - type: custom:hui-element
            card_type: custom:mini-graph-card
            entities:
              - entity: sensor.pi_hole_ads_blocked_today
                name: "Queries blocked today"
                unit: 'Blocked'
                color: '#FF0F00'
              - entity: sensor.pi_hole_dns_queries_today
              - entity: sensor.pi_hole_dns_queries_forwarded
                color: '#4DFF00'
            show:
              points: false
              legend: false
            line_width: 2
            hours_to_show: 72
          - entity: sensor.pi_hole_dns_queries_cached
            name: "Cached"
          - entity: sensor.pi_hole_dns_unique_domains
            name: "Unique Domains"

  - type: entities
    entities:
      - type: custom:hui-element
        card_type: picture
        image: 'https://new-desk.com/wp-content/uploads/2019/09/RPi-Logo-Landscape-Reg-SCREEN.png'
      - type: custom:decluttering-card
        template: system_monitor
        variables:
          - cpu_usage: rpi2_cpu_used
          - cpu_temps: rpi2_cpu_thermal_1_temperature
          - ram_usage: rpi2_ram_used_percent
      - type: custom:bar-card
        entities:
          - entity: sensor.rpi2_mnt_used_percent
            name: "External HDD"
            severity:
              - color: '#FF0F00'
                from: 91
                to: 100
          - entity: sensor.rpi2_used_percent
            name: "SD Storage"
            severity:
              - color: '#FF0F00'
                from: 91
                to: 100

  - type: entities
    show_header_toggle: false
    entities:
      - type: custom:hui-element
        card_type: picture
        image: 'https://brands.home-assistant.io/esphome/logo.png'
      - type: custom:hui-element
        card_type: glance
        entities:
          - binary_sensor.living_room
          - binary_sensor.bathroom
      - switch.restart_living_room
      - switch.restart_bathroom
