navy:

  # Fonts
  primary-font-family: 'Raleway,sans-serif'
  paper-font-common-base_-_font-family: "var(--primary-font-family)"
  paper-font-common-code_-_font-family: "var(--primary-font-family)"
  paper-font-body1_-_font-family: "var(--primary-font-family)"
  paper-font-subhead_-_font-family: "var(--primary-font-family)"
  paper-font-headline_-_font-family: "var(--primary-font-family)"
  paper-font-caption_-_font-family: "var(--primary-font-family)"
  paper-font-title_-_font-family: "var(--primary-font-family)"
  ha-card-header-font-family: "var(--primary-font-family)"

  # Text
  text-color: '#DCDCDC'
  primary-text-color: 'var(--text-color)'
  text-primary-color: 'var(--text-color)'
  secondary-text-color: "var(--text-color)"
  text-medium-light-color: 'var(--text-medium-color)'
  text-medium-color: '#848484'
  disabled-text-color: '#9C9C9C'
  primary-color: 'var(--accent-color)'

  # Main Colors
  app-header-background-color: 'var(--background-color)'
  accent-color: '#74A4F4'
  accent-medium-color: 'var(--accent-color)'

  # Background
  background-color: '#041623'
  primary-background-color: 'var(--background-color)'
  background-color-2: 'var(--background-color)'
  secondary-background-color: 'var(--background-color-2)'
  markdown-code-background-color: 'var(--background-color)'
  material-background-color: 'var(--light-primary-color)'

  # Card
  card-background-color: 'var(--background-color)'
  ha-card-background: 'var(--background-color)'
  ha-card-box-shadow: '5px 5px 20px -10px #020d15'
  ha-card-border-radius: "15px"
  border-color: 'none'

  # Icons
  paper-item-icon-color: '#DCDCDC'
  paper-item-icon-active-color: 'var(--accent-color)'

  # Sidebar
  sidebar-background-color: 'var(--background-image)'
  sidebar-icon-color: 'var(--text-color)'
  sidebar-selected-icon-color: 'var(--accent-color)'
  sidebar-selected-text-color: 'var(--text-color)'
  paper-listbox-background-color: 'var(--sidebar-background-color)'
  divider-color: 'var(--background-color)'
  light-primary-color: 'var(--ha-card-background)'

  # Sliders
  paper-slider-knob-color: 'var(--accent-color)'
  paper-slider-pin-color: 'var(--background-color-2)'
  paper-slider-active-color: 'var(--accent-color)'
  paper-slider-container-color: 'var(--background-color-2)'

  # Toggle
  paper-toggle-button-checked-bar-color: 'var(--accent-color)'
  mdc-theme-primary: 'var(--accent-color)'

  # Switch
  switch-unchecked-color: '#2D4363'
  switch-unchecked-track-color: 'var(--switch-unchecked-color)'
  switch-checked-button-color: '#065499'
  switch-checked-track-color: 'var(--switch-checked-button-color)'

  # Radio Button
  paper-radio-button-checked-color: 'var(--accent-color)'

  # Popups
  more-info-header-background: 'var(--secondary-background-color)'
  paper-dialog-background-color: 'var(--background-color)'

  # Tables
  table-row-background-color: 'var(--background-color)'
  table-row-alternative-background-color: 'var(--ha-card-background)'

  # Badges
  label-badge-background-color: 'var(--background-color)'
  label-badge-text-color: 'var(--text-primary-color)'
  label-badge-red: 'rgba(73,85,108,1)'
  label-badge-blue: 'rgba(26,137,245,1)'
  label-badge-green: 'rgba(0,202,139,1)'
  label-badge-yellow: 'rgba(222,176,107,1)'

  paper-input-container-focus-color: 'var(--accent-color)'

  # Mini Mediaplayer
  mini-media-player-base-color: 'var(--text-color)'
  mini-media-player-accent-color: 'var(--accent-color)'

  # Bar Card
  custom-bar-card-color: 'var(--accent-color)'

  # CodeMirror editor
  codemirror-keyword: '#042D40'
  codemirror-operator: 'var(--codemirror-keyword)'
  codemirror-variable: 'var(--codemirror-keyword)'
#  codemirror-variable-2:
#  codemirror-variable-3:
  codemirror-builtin: 'var(--codemirror-keyword)'
  codemirror-atom: 'var(--codemirror-keyword)'
#  codemirror-number:
  codemirror-def: '#A82D57'
  codemirror-string: '#2499F1'
  codemirror-string-2: 'var(--codemirror-string)'
  codemirror-comment: '#343444'
  codemirror-tag: '#343444'
#  codemirror-meta:
#  codemirror-attribute:
#  codemirror-property:
  codemirror-qualifier: 'var(--codemirror-keyword)'
  codemirror-type: '#A82D57'
