###
# Presence detection
# https://www.home-assistant.io/integrations/device_tracker
###

# Presence detection using Ping
- platform: ping
  hosts:
    yuval_ping: !secret yuval_ping
    tohar_ping: !secret tohar_ping
    fire_7: !secret fire_7
  count: 2
  scan_interval: 300
