#######################################
#               PERSONS               #
#######################################
###
# Define persons
# https://www.home-assistant.io/integrations/person
###

- name: "Yuval"
  id: yuval
  device_trackers:
    - device_tracker.yuval_ping
    - device_tracker.yuval
- name: "Tohar"
  id: tohar
  device_trackers:
    - device_tracker.tohar_ping
    - device_tracker.tohar
